### ISSUE TITLE
egan 15 secs before website

### ISSUE THREAD

**Issue by Hedgehawk11** [nicolaschan/schedules#30]
title

**Comment by nicolaschan** [comment]
Thanks for pointing this out! I've pushed the website time ahead by 15 seconds. Let me know if this fixed it or if there is any further adjustment needed.

**Comment by nicolaschan** [comment]
It's confusing! I think the wiki actually has it backwards :open_mouth: I'll update it to be accurate.

I noticed you put the adjustment back to 0 in your latest PR. Should it be 0 or go back to 15000?
