### ISSUE TITLE
Issue in Chap's Schedule

### ISSUE THREAD

**Issue by ActualBest** [nicolaschan/schedules#36]
https://github.com/nicolaschan/schedules/blob/90f129ad6087e59380f2f8c077603ec75ead3f61/chaparral-b/schedules.bell#L24C1-L25C17
Period 3 should be Period 6

Would it be possible to move this to edit.bell.plus (but still have a nice easy url) to make it easier for me to maintain?
Also, no one here knows how to spell Chaparral so changing it to bell.plus/chap-a and /chap-b would be great.

**Comment by nicolaschan** [comment]
Thanks for the bug report! 

Yes, I can transfer these to edit.bell.plus. I will send you a link to claim the schedules on your edit.bell.plus account. Should I send it to the same email that was used to request Chaparral?

**Comment by ActualBest** [comment]
Yes that would be great. Thanks so much!

**Comment by nicolaschan** [comment]
I've set them up and sent an email! Thanks so much for helping maintain the schedules for your school.
